### ISSUE TITLE
你好，cryptography 解密db文件 一直报错，请问是什么地方引起的

### ISSUE THREAD

**Issue by rallser** [HyperSine/forensic-qqtoken#3]
你好，cryptography 解密db文件 一直报错，请问是什么地方引起的:
Signature did not match digest.

**Comment by HyperSine** [comment]
这种情况你需要修改decrypt-database.py的第137行代码。
serialno参数就是Android设备的serialno，搞Android开发的都知道。
cpu_serial参数是安卓设备/proc/cpuinfo信息里Serial字段的值，不过大多数的情况下都没有，留空就好。

**Comment by rallser** [comment]
非常感谢您的回复，我已经安装要求填写了serialno ，143，144的字符串token 是不是应该写入token_info?

**Comment by HyperSine** [comment]
不要改，字符串“token”是硬编码的password，这东西不会变的

**Comment by rallser** [comment]
能添加下QQ联系下么 我的2310987320

**Comment by rallser** [comment]
我按照你的方法 试了好几次了 依然是Signature did not match digest. QQ安全中心是6.9.13

**Comment by HyperSine** [comment]
这样吧，麻烦提供一份mobiletoken.db文件，adb shell里getprop ro.serialno命令的截图，还有adb shell里cat /proc/cpuinfo的截图。
文件就发到我的邮箱吧。

**Comment by yzzsohu** [comment]
Traceback (most recent call last):
  File "e:\decrypt-database.py", line 143, in <module>
    wcdb_decrypt_first_page(raw_enc, 1024, g_device_salt, b'token') + \
  File "e:\decrypt-database.py", line 61, in wcdb_decrypt_first_page
    h.verify(hmac_sig)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\cryptography\hazmat\primitives\hmac.py", line 66, in verify
    ctx.verify(signature)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\cryptography\hazmat\backends\openssl\hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.
运行报错，大佬，这是啥情况了

**Comment by hexin46373** [comment]
the same error with me...
